#!/bin/bash

source /opt/self-healing/config.sh

#############################################
# Disk Usage Monitoring
#############################################

df -hP | awk 'NR>1 {print $5, $6}'| while read USAGE PARTITION

do

USAGE=${USAGE%\%}

if [ "$USAGE" -ge "$THRESHOLD" ]

then

#############################################
# Log Alert
#############################################

log_message "[WARNING] Disk usage exceeded threshold on $PARTITION ($USAGE%)."

#############################################
# Telegram Alert
#############################################

DISK_MSG="⚠️ *SelfHeal Linux*

━━━━━━━━━━━━━━━━━━

*DISK USAGE ALERT*

*Partition:* $PARTITION

*Usage:* ${USAGE}%

*Server:* $HOST

⚠ Threshold exceeded.

Please clean up unnecessary files.

*Time:* $(date '+%d-%b-%Y %I:%M:%S %p')

━━━━━━━━━━━━━━━━━━"

send_telegram "$DISK_MSG"

#############################################
# Email Alert
#############################################

mail -s "⚠ SelfHeal Linux | Disk Usage Alert" "$EMAIL" <<EOF

SelfHeal Linux Monitoring System

=========================================

DISK USAGE ALERT

=========================================

Server : $HOST

Partition : $PARTITION

Disk Usage : ${USAGE}%

Threshold : ${THRESHOLD}%

Status : WARNING

Recommended Action

• Remove unnecessary files

• Archive old logs

• Increase storage if required

Time

$(date)

=========================================

Generated by SelfHeal Linux

EOF

fi

done
