#!/bin/bash

source /opt/self-healing/config.sh

#############################################
# Services to Monitor
#############################################

SERVICES=(
sshd
httpd
firewalld
crond
NetworkManager
postfix
grafana-server
prometheus
)

#############################################
# Friendly Service Names
#############################################

get_service_name() {

case "$1" in

sshd)
echo "OpenSSH Server"
;;

crond)
echo "Crond"
;;

firewalld)
echo "Firewalld"
;;

NetworkManager)
echo "Network Manager"
;;

httpd)
echo "Apache HTTP Server"
;;

postfix)
echo "postfix"
;;

grafana-server)
echo "Grafana"
;;

prometheus)
echo "Prometheus Monitoring Server"
;;

*)
echo "$1"
;;

esac

}

#############################################
# Monitor Services
#############################################

for SERVICE in "${SERVICES[@]}"

do

DISPLAY_NAME=$(get_service_name "$SERVICE")

if ! systemctl is-active --quiet "$SERVICE"

then

#############################################
# Log Failure
#############################################

log_message "[CRITICAL] $DISPLAY_NAME is DOWN. Recovery started."

#############################################
# Telegram Failure Alert
#############################################

FAILURE_MSG="*SelfHeal Linux*

━━━━━━━━━━━━━━━━━━

*CRITICAL SERVICE ALERT*

*Service:* $DISPLAY_NAME

*Server:* $HOST

*Status:* DOWN

*Action:* Automatic recovery initiated.

*Time:* $(date '+%d-%b-%Y %I:%M:%S %p')

━━━━━━━━━━━━━━━━━━"

send_telegram "$FAILURE_MSG"

#############################################
# Restart Service
#############################################

systemctl restart "$SERVICE"

sleep 3

#############################################

# Check Recovery
#############################################

if systemctl is-active --quiet "$SERVICE"

then

#############################################
# Log Recovery
#############################################

log_message "[RECOVERED] $DISPLAY_NAME restarted successfully."

#############################################
# Telegram Recovery Alert
#############################################

RECOVERY_MSG="*SelfHeal Linux*

━━━━━━━━━━━━━━━━━━

*SERVICE RECOVERED*

*Service:* $DISPLAY_NAME

*Server:* $HOST

*Status:* RUNNING

✔ Automatic restart completed successfully.

*Time:* $(date '+%d-%b-%Y %I:%M:%S %p')

━━━━━━━━━━━━━━━━━━"

send_telegram "$RECOVERY_MSG"

#############################################
# Email Notification
#############################################

mail -s "SelfHeal Linux | Service Recovered - $DISPLAY_NAME" "$EMAIL" <<EOF

SelfHeal Linux Monitoring System

=========================================

SERVICE RECOVERY REPORT

=========================================

Service : $DISPLAY_NAME

Server : $HOST

Status : RUNNING

Recovery : Successful

Time : $(date)

Action Taken

• Service failure detected

• Automatic restart executed

• Health check passed

System Status

The monitored service is healthy and operational.

=========================================

Generated by SelfHeal Linux

EOF

else

#############################################
# Log Failure
#############################################

log_message "[FAILED] Unable to restart $DISPLAY_NAME."

fi

fi

done



